providers = ["node"]

[build]
cmds = [
  "cd ../shared && npm ci && npm run build",
  "npm ci",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"