providers = ["node"]

[build]
cmds = [
  "cd shared && npm ci && npm run build",
  "cd frontend && npm ci",
  "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"