services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: fantasy-postgres-test
    environment:
      POSTGRES_DB: fantasy_football_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: fantasy-redis-test
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Just test if we can build the shared package
  shared-test:
    image: node:18-alpine
    container_name: fantasy-shared-test
    working_dir: /app
    volumes:
      - ./shared:/app
    command: sh -c "npm install && npm run build"
    
networks:
  default:
    name: fantasy-network-test