providers = ["node"]

[build]
cmds = [
  "cd shared && npm ci && npm run build",
  "cd ai-service && npm ci",
  "cd ai-service && npm run build"
]

[start]
cmd = "cd ai-service && npm start"

[variables]
NODE_ENV = "production"