providers = ["node"]

[build]
cmds = [
  "cd shared && npm ci && npm run build",
  "cd backend && npm ci",
  "cd backend && npx prisma generate",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"